config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resource :user, only: [:show, :edit, :update, :new, :create]

  resources :restaurants, only: [:index, :edit, :update]

  resource :home, only: [:show]

  resource :sms, only: [:create]

  authenticated :user do
    root to: 'restaurants#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'homes#show', as: :unauthenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role?('admin')
        can :manage, :all
    else
        can :read, :all
    end    
  end
end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :user

  validates :city, :state, :zip_code, presence: true, if: :address?

  def coordinates
    if self.address?
      Geocoder.search("#{address} #{city}, #{state} #{zip_code}").first.coordinates
    else
      Geocoder.search(self.zip_code).first.coordinates
    end
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant

  validates :rating, presence: true

  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

  before_save :increment_times_had

  RATING_WEIGHT = 1.2
  TIMES_HAD_WEIGHT = -2


  def increment_times_had
    self.times_had += 1
  end

  def calculate_weighted_value
    times_had_weighted_value = TIMES_HAD_WEIGHT * times_had > -10 ? TIMES_HAD_WEIGHT - times_had : -10

    times_had_weighted_value - (RATING_WEIGHT * rating)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :ratings

  validates :name, presence: true

  accepts_nested_attributes_for :ratings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_one :address

  has_many :ratings
  has_many :restaurants, through: :ratings

  accepts_nested_attributes_for :address

  def role?(role)
    if self.role.nil?
      false
    else
      self.role.include? role.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :time_travel

  def time_travel
    if !params[:time_travel].nil?
      Timecop.travel(Time.at(params[:time_travel].to_i))
    else
      Timecop.return
    end
  end

  def after_sign_in_path_for(resource)
    if resource.role?('admin')
      admin_dashboard_path
    else
      edit_user_path
    end
  end

  def authenticate_admin_user!
    authenticate_user!
    unless current_user.role?(:admin)
      flash[:danger] = "Not authorized to access to this resouce!"
      redirect_to root_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
  end
end

app/controllers/restaurants_controller.rb
include RestaurantsHelper

class RestaurantsController < ApplicationController

  def index
    # Check to see if the user has eaten today by looking for an updated rating.
    # If yes, take them to the edit page, if no, show them something new.
    # Using UTC for database
    todays_user_rating = ratings_by_date_and_user(current_user).first
    yesterdays_rating = ratings_by_date_and_user(current_user, DateTime.now.utc - 1.day).first

    if current_user.address.nil? || current_user.address.zip_code.blank?
      flash[:warning] = "You're missing an address! #{link_to 'Click here', edit_user_path} to add one. Here's a random restaurant in the mean time..."
      @restaurant = random_restaurant(current_user, yesterdays_rating)
    elsif !todays_user_rating.nil?
      flash[:warning] = "Looks like you've eaten today! Please rate the restaurant if you haven't already."
      redirect_to edit_restaurant_path(todays_user_rating.restaurant.id)
    else
      @restaurant = random_restaurant(current_user, yesterdays_rating, current_user.address)
    end
  end

  def edit
    flash[:warning] = "Don't forget to click the 'I have eaten there now' button after you eat!!"
    @restaurant = Restaurant.find(params[:id])

    @user_rating = @restaurant.ratings.find_or_initialize_by(user_id: current_user.id)
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @user_rating = @restaurant.ratings.find_or_create_by(user_id: current_user.id)
    
    @user_rating.assign_attributes(rating_params)

    if @user_rating.save
      flash[:warning] = "Thanks for telling us how it was!"
      render :edit
    else
      flash[:danger] = @user_rating.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [ :new, :create ]

  def show
    @user = current_user
  end

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Successfully created your profile!'
      sign_in(@user)
      redirect_to after_sign_in_path_for(@user)
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @user = current_user

    if @user.address.nil?
      @user.address = Address.new
    end
  end

  def update
    @user ||= current_user

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    @user.assign_attributes(user_params)

    if @user.save
      flash[:success] = 'Updated successfully!'
      redirect_to user_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, address_attributes: [:city, :state, :address, :zip_code])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.places_service
    GooglePlacesService.new
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  def random_restaurant(user, yesterdays_rating, address=Address.first)
    service = ApplicationHelper.places_service

    if address.nil?
      # Cover case when we have no addresses in the database
      restaurants = Restaurant.all
    else
      restaurants = service.get_restaurants(address)
    end

    # Make a selection!
    restaurant_choice = sort_and_weight_restaurants(user, restaurants).first
    

    # Make sure we have a rating from yesterday and more than 1 restuarant
    # Don't want to get stuck in a loop.....
    unless yesterdays_rating.nil? && !(restaurants.count > 1)
      # Make a new selection if the restaurants match
      while restaurant_choice.id == yesterdays_rating.restaurant.id do
        restaurant_choice = sort_and_weight_restaurants(user, restaurants)
      end
    end

    restaurant_choice
  end

  def ratings_by_date_and_user(user, date_to_query = DateTime.now.utc)
    # Here to make finding ratings easier, since at one point we need to find yesterdays and todays rating.
    Rating.where(updated_at: date_to_query.beginning_of_day..date_to_query.end_of_day, user_id: user.id)
  end

  private

  def sort_and_weight_restaurants(user, restaurants)
    # Give each restaurant a random number, then remove the weight of the rating and times eaten to give us a value
    weight_restaurants = []

    restaurants.each do |restaurant|
      rating = Rating.find_by(user_id: user.id, restaurant_id: restaurant.id)
      weight_restaurants << {
        restaurant: restaurant,
        weight: rand(0..100) + (rating.nil? ? 0 : rating.calculate_weighted_value)
      }
    end

    restaurants.sort_by { |r| r[:weight] } 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/show.html.erb
<h1>Welcome, please sign up!</h1>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="
      #user-navbar" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
      </button>
      <a class="navbar-brand" href="#" style="text-decoration: none;">What's for Lunch?</a>
    </div>

    <div class="collapse navbar-collapse" id="user-navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Profile", user_path %></li>
        <li><%= link_to "What to eat?", restaurants_path %></li>
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsForLunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/nav' %>

<div class="container-fluid">
  <div class="row">
    <% flash.each do |key, value| %>
      <% puts key %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
  
  <%= yield %>
</div>

</body>
</html>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
    <h1><%= @restaurant.name %></h1>
  </div>
</div>

<br />
<br />

<div class="row">
  <%= form_for @user_rating, url: restaurant_path(@restaurant), method: :patch do |f| %>
    <div class="row">
      <div class="col-xs-1 col-xs-offset-4">
        <%= f.label :rating, "How was it?" %>
      </div>
      <div class="col-xs-2">
        <%= f.number_field :rating, within: 0..5, step: 0.5 %>
      </div>
    </div>

    <div class="row" style="margin-top: 15px;">
      <div class="col-xs-4 col-xs-offset-4">
        <%= f.submit "I've eaten there now" %>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4"><h1><%= @restaurant.name %></h1></div>
</div>
<div class="row">
  <div class="col-xs-6 col-xs-offset-4" style="padding: 15px 0px;">
    <%= @user_rating.nil? ? "You've never eaten here, you should try it!" : "You've eaten here #{@user_rating.times_had} time(s)" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-offset-4 col-xs-6">
    <% 
      # Hacky way to make sure we keep track of traveling through time. 
      should_time_travel = params[:time_travel].nil? ? {} : { time_travel: DateTime.now.to_i } 
    %>
    <%= link_to 'I want to eat here!', edit_restaurant_path({id: @restaurant.id}.merge(should_time_travel)), class: 'button' %>
    <%= link_to 'Give me something else', restaurants_path({}.merge(should_time_travel)), class: 'button' %>
  </div>
</div>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :email %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :password %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :password %>
    </div>
  </div>

  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :password_confirmation %>
    </div>
  </div>

  <%= f.fields_for :address, @user.address do |a| %>
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :address %>
      </div>
      <div class="col-xs-4">
        <%= a.text_field :address %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :city %>
      </div>
      <div class="col-xs-4">
        <%= a.text_field :city %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :state %>
      </div>
      <div class="col-xs-4">
        <%= a.text_field :state %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :zip_code %>
      </div>
      <div class="col-xs-4">
        <%= a.text_field :zip_code %>
      </div>
    </div>
  <% end %>

  <div class = "row">
    <div class="col-xs-3 col-xs-offset-3" style="margin-top: 15px;">
      <%= f.submit "Update" %>
    </div>
  </div>   
<% end %>

app/views/users/new.html.erb
<%= form_for :user, url: '/user', method: :post do |f| %>
  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :email %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :password %>
    </div>
    <div class="col-xs-4">
      <%= f.password_field :password %>
    </div>
  </div>

  <div class = "row">
    <div class="col-xs-2 col-xs-offset-1">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-xs-4">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <%= f.fields_for :address_attributes do |a| %>
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :address %> (Optional)
      </div>
      <div class="col-xs-4">
        <%= a.text_field :address %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :city %> (Optional)
      </div>
      <div class="col-xs-4">
        <%= a.text_field :city %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :state %> (Optional)
      </div>
      <div class="col-xs-4">
        <%= a.text_field :state %>
      </div>
    </div>
    
    <div class = "row">
      <div class="col-xs-2 col-xs-offset-1">
        <%= a.label :zip_code %>
      </div>
      <div class="col-xs-4">
        <%= a.text_field :zip_code %>
      </div>
    </div>
  <% end %>

  <div class = "row">
    <div class="col-xs-3 col-xs-offset-3" style="margin-top: 15px;">
      <%= f.submit "Create" %>
    </div>
  </div>   
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <table class="table">
      <tr>
        <th></th>
        <td><%= link_to "Edit", edit_user_path %></td>
      </tr>
      <tr>
        <th class="">Email</th>
        <td class=""><%= @user.email %></td>
      </tr>
      <% unless @user.address.nil? %>
        <tr>
          <th class="">Address</th>
          <td class=""><%= @user.address.address %></td>
        </tr>
        <tr>
          <th class="">State</th>
          <td class=""><%= @user.address.state %></td>
        </tr>
        <tr>
          <th class="">City</th>
          <td class=""><%= @user.address.city %></td>
        </tr>
        <tr>
          <th class="">Zip Code</th>
          <td class=""><%= @user.address.zip_code %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>